

version: '3.1'

services:
  account-service:
    image: madhukargunda/account-service
    ports:
      - 80:2222
    container_name: account-service
    restart:
      on-failure
    networks:
      - back-end
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure  

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "7001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - back-end


networks: 
  back-end:
    driver: overlay
    
  
